version: "3"
services:
#  fastapi:
#    container_name: fastapi_automl
#    build:
#      context: backend/
#      dockerfile: Dockerfile
#    command: bash -c "python3 data_loader.py && gunicorn -b 0.0.0.0:7013 -w 2 -t 360 -k uvicorn.workers.UvicornWorker main:app --max-requests 250 --max-requests-jitter 50 --access-logfile -"
#    ports:
#      - '7007:7007'
#    restart: on-failure
#    networks:
#      - auto_ml_network
#    depends_on:
#      - mongo
#    environment:
#      CSV_FILE_PATH: dataset/main/credit_train.csv
#      MONGODB_URL: mongodb://user:pass@mongo:27017

  mongo:
    container_name: mongo_automl
    image: mongo
    hostname: mongo
#    networks:
#      - auto_ml_network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

networks:
  auto_ml_network: